#!/usr/bin/env -S ansible-playbook -i hosts --become -c pi
---
- name: Ansible Playbook for configuring Pi-Hole on Raspberry Pi
  hosts: webservers
  roles:
    - pi
  remote_user: pi
  become: yes

  handlers:
    - name: restart ntp
      service: name=ntp state=restarted

    - name: force ntp update
      shell: "service ntp stop && ntpdate -s {{ timeserver  }} && service ntp start"
